### ISSUE TITLE
Debug binaries are built when CMAKE_BUILD_TYPE=Release with MSVC

### ISSUE THREAD

**Issue by vladislavrv** [vladislavrv/MatrixGame#12]
The title is self explaining. Looks like something wrong with flags/options in cmake files.
Works fine with GCC.

**Comment by TheNormalnij** [comment]
Seems `CMAKE_BUILD_TYPE=Release` doesn't work now.
* It request NOMINMAX definition (fixable)
* Internal compiler error in VS 2022

**Comment by vladislavrv** [comment]
Issue is fixed quite some time ago ([here](https://github.com/vladislavrv/MatrixGame/commit/d8b6bef33a8e373b3a49408e34ebd58eae4bdb55)), thanks @TheNormalnij for the provided fix.
